### ISSUE TITLE
Segfault at ERTConnect initialization

### ISSUE THREAD

**Issue by HiroIshida** [HiroIshida/plainmp#36]
Address sanitizer's output
```gdb
h-ishida@azarashi:~/cpp/plainmp/python/tests$ python3 test_ompl_solver.py 
/usr/lib/python3/dist-packages/requests/__init__.py:89: RequestsDependencyWarning: urllib3 (2.2.2) or chardet (3.0.4) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({}) doesn't match a supported "
Debug:   RRTConnect: Planner range detected to be 4.607101
Info:    RRTConnect: Starting planning with 1 states already in datastructure
Info:    RRTConnect: Created 25 states (6 start + 19 goal)
Info:    Solution found in 0.151303 seconds
AddressSanitizer:DEADLYSIGNAL
=================================================================
==3954358==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000000 (pc 0x7f54bcad6104 bp 0x7ffe25a018b0 sp 0x7ffe25a00ff8 T0)
==3954358==The signal is caused by a READ memory access.
==3954358==Hint: address points to the zero page.
    #0 0x7f54bcad6103  (/lib/x86_64-linux-gnu/libc.so.6+0x185103)
    #1 0x7f54bcc7095e in __interceptor_memcmp ../../../../src/libsanitizer/sanitizer_common/sanitizer_common_interceptors.inc:846
    #2 0x7f54aba35f5b in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::compare(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const (/lib/x86_64-linux-gnu/libstdc++.so.6+0x15bf5b)
    #3 0x7f5466ee4941 in bool std::operator< <char, std::char_traits<char>, std::allocator<char> >(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) /usr/include/c++/9/bits/basic_string.h:6232
    #4 0x7f5466eea7f0 in std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >::operator()(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const /usr/include/c++/9/bits/stl_function.h:386
    #5 0x7f5466f3b6df in std::_Rb_tree<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::shared_ptr<ompl::base::GenericParam> >, std::_Select1st<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::shared_ptr<ompl::base::GenericParam> > >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::shared_ptr<ompl::base::GenericParam> > > >::_M_lower_bound(std::_Rb_tree_node<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::shared_ptr<ompl::base::GenericParam> > >*, std::_Rb_tree_node_base*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) /usr/include/c++/9/bits/stl_tree.h:1934
    #6 0x7f5466f38a38 in std::_Rb_tree<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::shared_ptr<ompl::base::GenericParam> >, std::_Select1st<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::shared_ptr<ompl::base::GenericParam> > >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::shared_ptr<ompl::base::GenericParam> > > >::lower_bound(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) /usr/include/c++/9/bits/stl_tree.h:1287
    #7 0x7f5466f35b56 in std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::shared_ptr<ompl::base::GenericParam>, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::shared_ptr<ompl::base::GenericParam> > > >::lower_bound(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) /usr/include/c++/9/bits/stl_map.h:1258
    #8 0x7f5466f3151c in std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::shared_ptr<ompl::base::GenericParam>, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::shared_ptr<ompl::base::GenericParam> > > >::operator[](std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) /usr/include/c++/9/bits/stl_map.h:495
    #9 0x7f5466f2c197 in void ompl::base::ParamSet::declareParam<double>(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, ompl::base::SpecificParam<double>::SetterFn const&, ompl::base::SpecificParam<double>::GetterFn const&) /opt/ros/noetic/include/ompl-1.6/ompl/base/GenericParam.h:234
    #10 0x7f5466f26ba9 in void ompl::base::Planner::declareParam<double, ompl::geometric::ERTConnect*, void (ompl::geometric::ERTConnect::*)(double), double (ompl::geometric::ERTConnect::*)() const>(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, ompl::geometric::ERTConnect* const&, void (ompl::geometric::ERTConnect::* const&)(double), double (ompl::geometric::ERTConnect::* const&)() const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) /opt/ros/noetic/include/ompl-1.6/ompl/base/Planner.h:374
    #11 0x7f5466f180cb in ompl::geometric::ERTConnect::ERTConnect(std::shared_ptr<ompl::base::SpaceInformation> const&) /home/h-ishida/cpp/plainmp/third/ompl-ertconnect/ertconnect/src/ERTConnect.cpp:47
    #12 0x7f5466d481fa in void __gnu_cxx::new_allocator<ompl::geometric::ERTConnect>::construct<ompl::geometric::ERTConnect, std::shared_ptr<ompl::base::SpaceInformation>&>(ompl::geometric::ERTConnect*, std::shared_ptr<ompl::base::SpaceInformation>&) /usr/include/c++/9/ext/new_allocator.h:146
    #13 0x7f5466d42c91 in void std::allocator_traits<std::allocator<ompl::geometric::ERTConnect> >::construct<ompl::geometric::ERTConnect, std::shared_ptr<ompl::base::SpaceInformation>&>(std::allocator<ompl::geometric::ERTConnect>&, ompl::geometric::ERTConnect*, std::shared_ptr<ompl::base::SpaceInformation>&) (/home/h-ishida/cpp/plainmp/python/plainmp/_plainmp.cpython-38-x86_64-linux-gnu.so+0x32cc91)
    #14 0x7f5466d3e7d8 in std::_Sp_counted_ptr_inplace<ompl::geometric::ERTConnect, std::allocator<ompl::geometric::ERTConnect>, (__gnu_cxx::_Lock_policy)2>::_Sp_counted_ptr_inplace<std::shared_ptr<ompl::base::SpaceInformation>&>(std::allocator<ompl::geometric::ERTConnect>, std::shared_ptr<ompl::base::SpaceInformation>&) /usr/include/c++/9/bits/shared_ptr_base.h:548
    #15 0x7f5466d34ee1 in std::__shared_count<(__gnu_cxx::_Lock_policy)2>::__shared_count<ompl::geometric::ERTConnect, std::allocator<ompl::geometric::ERTConnect>, std::shared_ptr<ompl::base::SpaceInformation>&>(ompl::geometric::ERTConnect*&, std::_Sp_alloc_shared_tag<std::allocator<ompl::geometric::ERTConnect> >, std::shared_ptr<ompl::base::SpaceInformation>&) /usr/include/c++/9/bits/shared_ptr_base.h:679
    #16 0x7f5466d2b6e8 in std::__shared_ptr<ompl::geometric::ERTConnect, (__gnu_cxx::_Lock_policy)2>::__shared_ptr<std::allocator<ompl::geometric::ERTConnect>, std::shared_ptr<ompl::base::SpaceInformation>&>(std::_Sp_alloc_shared_tag<std::allocator<ompl::geometric::ERTConnect> >, std::shared_ptr<ompl::base::SpaceInformation>&) /usr/include/c++/9/bits/shared_ptr_base.h:1344
    #17 0x7f5466d19221 in std::shared_ptr<ompl::geometric::ERTConnect>::shared_ptr<std::allocator<ompl::geometric::ERTConnect>, std::shared_ptr<ompl::base::SpaceInformation>&>(std::_Sp_alloc_shared_tag<std::allocator<ompl::geometric::ERTConnect> >, std::shared_ptr<ompl::base::SpaceInformation>&) /usr/include/c++/9/bits/shared_ptr.h:359
    #18 0x7f5466d0daf4 in std::shared_ptr<ompl::geometric::ERTConnect> std::allocate_shared<ompl::geometric::ERTConnect, std::allocator<ompl::geometric::ERTConnect>, std::shared_ptr<ompl::base::SpaceInformation>&>(std::allocator<ompl::geometric::ERTConnect> const&, std::shared_ptr<ompl::base::SpaceInformation>&) (/home/h-ishida/cpp/plainmp/python/plainmp/_plainmp.cpython-38-x86_64-linux-gnu.so+0x2f7af4)
    #19 0x7f5466cf4fe8 in std::shared_ptr<ompl::geometric::ERTConnect> std::make_shared<ompl::geometric::ERTConnect, std::shared_ptr<ompl::base::SpaceInformation>&>(std::shared_ptr<ompl::base::SpaceInformation>&) (/home/h-ishida/cpp/plainmp/python/plainmp/_plainmp.cpython-38-x86_64-linux-gnu.so+0x2defe8)
    #20 0x7f5466ced229 in plainmp::ompl_wrapper::ERTConnectPlanner::ERTConnectPlanner(std::vector<double, std::allocator<double> > const&, std::vector<double, std::allocator<double> > const&, std::shared_ptr<plainmp::constraint::IneqConstraintBase>, unsigned long, plainmp::ompl_wrapper::ValidatorConfig const&) /home/h-ishida/cpp/plainmp/cpp/plainmp/ompl/ompl_thin_wrap.hpp:239
    #21 0x7f5466d2377f in plainmp::ompl_wrapper::ERTConnectPlanner* pybind11::detail::initimpl::construct_or_initialize<plainmp::ompl_wrapper::ERTConnectPlanner, std::vector<double, std::allocator<double> >, std::vector<double, std::allocator<double> >, std::shared_ptr<plainmp::constraint::IneqConstraintBase>, unsigned long, plainmp::ompl_wrapper::ValidatorConfig, 0>(std::vector<double, std::allocator<double> >&&, std::vector<double, std::allocator<double> >&&, std::shared_ptr<plainmp::constraint::IneqConstraintBase>&&, unsigned long&&, plainmp::ompl_wrapper::ValidatorConfig&&) (/home/h-ishida/cpp/plainmp/python/plainmp/_plainmp.cpython-38-x86_64-linux-gnu.so+0x30d77f)
AddressSanitizer: nested bug in the same thread, aborting.
```

**Comment by HiroIshida** [comment]
It was my mistake.
